[package]
name = "davis"
version = "0.1.0"
authors = ["Simon Persson <simon@flaskpost.me>"]
edition = "2018"

[[bin]]
name = "davis"
path = "src/main.rs"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
libc = "0.2"
mpd = { git = "https://github.com/SimonPersson/rust-mpd.git" }
clap = "3.0.0-beta.2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"

[build-dependencies]
toml = "0.5"
clap_generate = "3.0.0-beta.2"
clap = "3.0.0-beta.2"
log = "0.4"
libc = "0.2"
mpd = { git = "https://github.com/SimonPersson/rust-mpd.git" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sixel_bench"
harness = false
