[package]
name = "davis"
version = "0.1.0"
authors = ["Simon Persson <simon@flaskpost.me>"]
edition = "2018"

[lib]
name = "sixel"
path = "src/sixel/lib.rs"

[[bin]]
name = "davis"
path = "src/main.rs"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
libc = "0.2"
mpd = { git = "https://github.com/SimonPersson/rust-mpd.git" }
textwrap = { version = "0.13", default-features = false }
clap = "3.0.0-beta.2"
image = { version = "0.23", default-features = false, features = ["jpeg", "png"] }
imagequant  = "3"
rgb  = "0.8"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sixel_bench"
harness = false
